
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { CustomHeader } from "@/components/header"
import { CustomSidebar } from "@/components/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function UitvoeringLayout({ children }: { children: React.ReactNode }) {
  return <div className="theme-uitvoering">
    {/* <CustomHeader></CustomHeader> */}
    <div>
      <CustomSidebar></CustomSidebar>
      <div className="max-w-[70vw] ml-auto">
        {children}

      </div>
    </div>
  </div>;
}
